---
channel: stable
addons:
  zwave2mqtt:
    repository: hassio-addons/addon-zwave2mqtt
    target: zwave2mqtt
    image: hassioaddons/zwave2mqtt-{arch}
  zwave2mqtt-dev:
    repository: hassio-addons/addon-zwave2mqtt-dev
    target: zwave2mqtt
    image: hassioaddons/zwave2mqtt-{arch}